### PR TITLE
Throws an exception for any non-successful HTTP response.

### LINKED ISSUE #62: Client doesn't throw Taxjar exceptions during outage
Howdy!

This is happening during a major outage (1/11/21, 13:30-14:30 EST). Here's a log of the issue:

```
irb(main):014:0> Taxjar::Version.to_s
=> "2.6.1"
irb(main):015:0> c = ::Taxjar::Client.new(api_key: ENV['TAXJAR_API_KEY'])
irb(main):016:0> c.categories
=> []
irb(main):017:0> c.rates_for_location zipcode: 95060, city: 'Santa Cruz', state: 'CA', country: 'US'
Traceback (most recent call last):
        1: from (irb):17
NoMethodError (undefined method `each' for nil:NilClass)
irb(main):018:0>
```

I've traced it back to `model_attributes`, in this case it's a `set_attributes` call from trying to build a `Taxjar::Rate`, when I tried `tax_for_order` it was a `Taxjar::Tax`, so I don't think it's specific to the model.

(It would be swell if there was an option to get verbose http output for situations like these too.)

Thanks much!

### PR DESCRIPTION
**Pull request by poops**
This fixes #62 by throwing an exception for any non-successful HTTP response.

### CODE REVIEW

File: lib/taxjar/api/request.rb [hunk 1]
```diff
@@ -72,17 +72,16 @@ def symbolize_keys!(object)
...
+        def fail_or_return_response_body(response, body)
+          if body.nil?
+            fail(Taxjar::Error.for_json_parse_error(response.code))
+          elsif response.status.success?
+            body[object_key.to_sym]
+          elsif !(klass = Taxjar::Error::ERRORS[response.code]).nil?
+            fail(klass.from_response(body))
+          else
+            message = HTTP::Response::Status::REASONS[response.code] || "Unknown Error"
+            fail(HTTP::Error, message)
```
Comment (fastdivision) [inline lib/taxjar/api/request.rb:84]: @poops Based on our documentation around [error handling](https://github.com/taxjar/taxjar-ruby#error-handling), should we consider raising a `Taxjar::Error` instead with additional details around `HTTP::Error` to ensure minimal changes by a developer using the API client?

Comment (poops) [reply lib/taxjar/api/request.rb:84]: I wasn't sure since the [API docs](https://developers.taxjar.com/api/reference/#errors) state a specific list of errors, and some errors may not be coming from the API server.

Though based on the error handling you linked, I agree raising `Taxjar::Error` would be a safer bet.

**Review by jakedjohnson — DISMISSED** [review]

File: lib/taxjar/api/request.rb [hunk 2]
```diff
@@ -72,17 +72,16 @@ def symbolize_keys!(object)
...
-            klass.from_response(body)
+        def fail_or_return_response_body(response, body)
+          if body.nil?
+            fail(Taxjar::Error.for_json_parse_error(response.code))
+          elsif response.status.success?
+            body[object_key.to_sym]
+          elsif !(klass = Taxjar::Error::ERRORS[response.code]).nil?
+            fail(klass.from_response(body))
+          else
+            message = HTTP::Response::Status::REASONS[response.code] || "Unknown Error"
```
Comment (fastdivision) [inline lib/taxjar/api/request.rb:83]: @poops If a developer rescues an `Unknown Error` exception, can we return back the response code as well? We can assume a class name (`Taxjar::Error`), message, and response code may want to be examined.

Comment (fastdivision) [reply lib/taxjar/api/request.rb:83]: Actually return a code either way for a generic `Taxjar::Error` in this `else` block.

**Review by fastdivision — APPROVED** [review]
Looks good to me 👍 Thanks @poops!

**Review by cas27 — APPROVED** [review]
